### PR TITLE
UpdateConfig, a utility to bring an existing .config file in line with current template

### PR DESCRIPTION
**Pull request by g7gpr**
This utility reads in a station .config file and parses it. It then reads in a template configuration file, and populates the template file with the values from the station .config file. 

It can handle edge cases, such as options that are commented out in the template file, but in force in the station config file. 

This is the first few lines of the station .config file for AU0006. 

```
; IMPORTANT: There always must be at least one space after the argument value and before the semicolon in front of the comment.
; For example, "parameter: value ; comment" is correct, while "parameter: value; comment" is incorrect.

[System]

stationID: AU0006
latitude: -32.0 ; WGS84 +N  (degrees )
longitude: 116.0 ; WGS84 +E (degrees)
elevation: 35 ; mean sea level EGM96 geoidal datum, not WGS84 ellipsoidal (meters)
```

When the command 

```
python -m Utils.UpdateConfig ~/source/RMS/.config -t ~/source/RMS/.configTemplate
```
The file is transformed as shown below.

```
; IMPORTANT: Unlike other RMS files, the '.config' file is never automatically
; updated. When changes are introduced to the config file in RMS, these changes
; will NOT be automatically reflected in the active '.config' file on
; individual machines. Users should manually update their '.config' file if
; changing any option from its default value is desired, or to simply stay
; up-to-date. If an option is missing from the config file, a default value
; will be automatically applied.
; An up-to-date template config '.configTemplate' file, containing the current
; options, is located in the RMS root directory.
; Run python -m Utils.AuditConfig to compare the .config file to the template.

[System]

; The assigned station ID
stationid: AU0006

; WGS84 +N (degrees)
latitude: -32.0

; WGS84 +E (degrees)
longitude: 116.0

; Mean sea level EGM96 geoidal datum, not WGS84 ellipsoidal (meters)
; Can be obtained from Google Earth or other apps. Raw GPS altitude should not
; be used as the software converts from EGM96 to WGS84 internally.
elevation: 33

; Should be set only if full CAMS compatibility is desired
cams_code: 0
```

Options that are commented out in the template such as 

```
; The description shown on the weblog (e.g. location, pointing direction)
weblog_description: none

; Server will generate obfuscated coordinates for public datasets.
; Optionally, uncomment and populate the three parameters below to use a
; specific public location if desired. The recommended precision is two decimal
; places for latitude and longitude, and ~10 m for elevation.
;
; WGS84 +N (degrees)
; public_latitude: 0.0
;
; WGS84 +E (degrees)
; public_longitude: 0.0
;
; mean sea level EGM96 (meters)
; public_elevation: 0.0
```

will be uncommented if they are required 

```
; The description shown on the weblog (e.g. location, pointing direction)
weblog_description: Baldivis (testing)

; Server will generate obfuscated coordinates for public datasets.
; Optionally, uncomment and populate the three parameters below to use a
; specific public location if desired. The recommended precision is two decimal
; places for latitude and longitude, and ~10 m for elevation.
;
; WGS84 +N (degrees)
public_latitude: -32.3310873
;
; WGS84 +E (degrees)
public_longitude: 115.8165646
;
; mean sea level EGM96 (meters)
public_elevation: 40
```

The tool can also be run interactively 

```
python -m Utils.UpdateConfig ~/source/RMS/.config -t ~/source/RMS/.configTemplate -i
```
or can be called from another program.

A rolling backup scheme is implemented, with a default of 5 backups.

```
-rw-r--r-- 1 david david 20K Aug 16 15:24 .config
-rw-r--r-- 1 david david 20K Aug 16 15:24 .config_1
-rw-r--r-- 1 david david 20K Aug 16 15:22 .config_2
-rw-r--r-- 1 david david 20K Aug 16 15:20 .config_3
-rw-r--r-- 1 david david 20K Aug 16 15:19 .config_4
-rw-r--r-- 1 david david 20K Aug 16 15:18 .config_5
-rw-r--r-- 1 david david 19K Aug 16 07:35 .configTemplate
```

Options which are in the station config file, but not in the template will be inserted at the end of the appropriate section. When run interactively, each option can be selected individually.

### CODE REVIEW

**Comment by Cybis320** [comment]
This is awesome. Will test. 
I was hesitant to go that route because of the 'you-shall-not-touch' philosophy around .config. But as long as operators are in control of transfer operation, I don't see the harm. It should be made clear that if operators have notes for themselves or have commented out alternatives options (says several alternative url for device), these will not transfer. Not sure if folks do that though.

**Comment by g7gpr** [comment]
With a bit of additional work, I could probably transfer bespoke comments across, but that's the opposite of the intent of this tool.

**Comment by Cybis320** [comment]
I was thinking more about a simple caution message explaining what will be retain and what will be lost exactly.

**Comment by g7gpr** [comment]
That is definitely a good idea; perhaps I should rewrite the command line arguments so that the default is to run interactively, with warnings, and a command line switch to run silently.

**Comment by Cybis320** [comment]
Testing this now.
It's giving me this error. I think line 373 should handle 'None':
```
or bespoke comments will be lost. 


Would you like to proceed?y
Option:event_monitor_check_interval_fast from Section:Upload was not found in station .config, set to 3
Traceback (most recent call last):
  File "/Users/lucbusquin/anaconda3/envs/RMS/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/lucbusquin/anaconda3/envs/RMS/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/lucbusquin/Projects/RMS/Utils/UpdateConfig.py", line 568, in <module>
    updateConfig(cml_args.config_file_path, cml_args.template, interactive)
  File "/Users/lucbusquin/Projects/RMS/Utils/UpdateConfig.py", line 482, in updateConfig
    new_config_path = populateTemplateConfig(config_template_file_path, config_file_path, sections_list,
  File "/Users/lucbusquin/Projects/RMS/Utils/UpdateConfig.py", line 373, in populateTemplateConfig
    if option.lower() in options_list_of_lists[section_number]:
AttributeError: 'NoneType' object has no attribute 'lower'
```

I tried :
```python 
            if option and option.lower() in options_list_of_lists[section_number]:
```
it solves the issue but I haven't looked at the implications.

The case of the option fields is not preserved, e.g. stationID>stationid. Not sure if it matters (I think not)

It's not preserving some of the layout of the original template (missing blank line)
```
; Gstreamer decoder element to use. Only applicable if media_backend is gst.
; Examples: decodebin, avdec_h264, nvh264dec
gst_decoder: avdec_h264

# Location of the raw videos to be saved to disk (None means no saving).
raw_video_dir: None

# Save the raw video to the night directory.
# If True, the raw_video_dir is ignored.
raw_video_dir_night: False
```
became
```
; Gstreamer decoder element to use. Only applicable if media_backend is gst.
; Examples: decodebin, avdec_h264, nvh264dec
gst_decoder: avdec_h264
# Location of the raw videos to be saved to disk (None means no saving).
raw_video_dir: None
# Save the raw video to the night directory.
# If True, the raw_video_dir is ignored.
raw_video_dir_night: False
```
I'll keep testing. Thank you for your work on this. I think it's super useful.

**Comment by g7gpr** [comment]
Would you be able to email the .config file you ran it on to cause this error? Some line is being identified as being an option line when it is not. I had this happen a few times, but I thought I had handled all the edge cases.

**Comment by g7gpr** [comment]
OK, it should handle new sections in the template now. Next I'll preserve the option cases.

**Comment by g7gpr** [comment]
OK, very grateful for any further testing you can carry out.

**Comment by g7gpr** [comment]
Case is now preserved 

```
[System]

; The assigned station ID
stationID: XX0001

; WGS84 +N (degrees)
latitude: 43

; WGS84 +E (degrees)
longitude: -81

; Mean sea level EGM96 geoidal datum, not WGS84 ellipsoidal (meters)
; Can be obtained from Google Earth or other apps. Raw GPS altitude should not
; be used as the software converts from EGM96 to WGS84 internally.
elevation: 327

; Should be set only if full CAMS compatibility is desired
cams_code: 0
```
becomes

```
[System]

; The assigned station ID
stationID: AU0028

; WGS84 +N (degrees)
latitude: -34.xyz

; WGS84 +E (degrees)
longitude: 116.xyz

; Mean sea level EGM96 geoidal datum, not WGS84 ellipsoidal (meters)
; Can be obtained from Google Earth or other apps. Raw GPS altitude should not
; be used as the software converts from EGM96 to WGS84 internally.
elevation: 200

; Should be set only if full CAMS compatibility is desired
cams_code: 0
```

Missing sections are copied in

File before upgrade ends with 
```
[Thumbnails]

; Thumbnail binning
thumb_bin:      4
; How many images will be stacked per each thumbnail
thumb_stack:    5
; Number of thumbnails in each row
thumb_n_width: 10


[Stack]

; Whether to apply the mask to stack or not
stack_mask: false

```
Now ends with 
```
[Thumbnails]

; Thumbnail binning
thumb_bin: 4

; How many images will be stacked per each thumbnail
thumb_stack: 5

; Number of thumbnails in each row
thumb_n_width: 10



[Stack]

; Whether to apply the mask to stack or not
stack_mask: false



[Timelapse]

; Automatically generate a timelapse using all FF files
timelapse_generate_captured: true


[Colors]

; color palette to use for various charts -can be any matplotlib color scheme
; other options are gist_ncar, rainbow, gist_rainbow, inferno
shower_color_map: gist_ncar
```

If a new section is inserted part way through the template

```
[Build]

; Compiler arguments for cython
rpi_weave: -O3 -mfpu=neon -funsafe-loop-optimizations -ftree-loop-if-convert-stores
linux_pc_weave: -O3
win_pc_weave: -Wall

[InsertedSection]

; Dummy section for testing puposes
Capitalized_Option: value


[Upload]

; Flag for enabling/disabling upload to meteor server
upload_enabled: true
```

It appears in the stations .config

```
[Build]

; Compiler arguments for cython
rpi_weave: -O3 -mfpu=neon -funsafe-loop-optimizations -ftree-loop-if-convert-stores
linux_pc_weave: -O3
win_pc_weave: -Wall

[InsertedSection]

; Dummy section for testing puposes
Capitalized_Option: value

[Upload]

; Flag for enabling/disabling upload to meteor server
upload_enabled: false
```

**Comment by Cybis320** [comment]
I'm still seeing issues with missing blank lines. I think the issue is that when a blank line is detected, the code sets blank_line = True, but it doesn't actually write anything to the output file for blank lines. The else clause that adds the line with a newline character is only reached if the line is not blank, not a comment, not a section header, and not an uncommented line.

Here are some suggestions:

When a blank line is detected, immediately sets output_line = "\n" to preserve the blank line.
At the end of all the checks, if output_line is still empty (meaning none of the specific conditions were met), set output_line to the original line plus a newline character.
Move the  output_file_handle.write(output_line) call outside of the else clause, ensuring that all lines (including blank lines) are written to the output file.

These changes should ensure that blank lines from the template are preserved in the output config file:

From:
https://github.com/CroatianMeteorNetwork/RMS/blob/110cb542fb566c1394af49b1d8f61c18b2ed8bdb/Utils/UpdateConfig.py#L372-L374

To:
```python
       if not line.strip():
            blank_line = True
            output_line = "\n"  # Preserve the blank line
```

From:
https://github.com/CroatianMeteorNetwork/RMS/blob/110cb542fb566c1394af49b1d8f61c18b2ed8bdb/Utils/UpdateConfig.py#L444-L454

To:
```python
          else:
                if interactive:
                    print("From new section {} adding new line {}".format(template_sections_list[-1],line))
                output_line = line + "\n"

        if not output_line:
            output_line = line + "\n"

        output_file_handle.write(output_line)
```

**Comment by g7gpr** [comment]
Unable to replicate the behaviour you describe.

**Pull request closed without merging**
