### PR TITLE
Comment out lines related to git repo as a triage measure for multicam

### PR DESCRIPTION
**Pull request by g7gpr**
Issue #434 reports that git repo cannot be ascertained in multicam environment and prevents capture start. This PR comments out the lines of code which are causing the crash.

### CODE REVIEW

**Comment by g7gpr** [comment]
OK - the problem is slightly more subtle. The old version of multicam launches RMS in ~/source/Stations/STAID; which leads to all kinds of strange things. New version will launch from ~/source/RMS and then point to the correct .config file.

**Comment by g7gpr** [comment]
Testing this change now, launching in ~/source/Stations/AU000A

**Comment by g7gpr** [comment]
I've tested this launching in both ~/source/Stations/STATID, and also from ~/source/RMS and capture is running. I'll let the capture finish, check the results and then this is ready to merge.

**Comment by g7gpr** [comment]
2 Captures completed, one launched from ~/source/RMS. and one launched with the working directory ~/source/Stations/STATID.

**Comment by Cybis320** [comment]
It's just that the old startCap files are not automatically updated and need to be manually updated, no?

**Comment by g7gpr** [comment]
They are not automatically updated. The files were originally distributed by emailing zip files around. Because there were different implementations, I don't think we should update anything remotely, just ask station operators to manually update their systems once everything is stable.

**Comment by g7gpr** [comment]
Closing as handled by commit cdec45adf64585586a66399b9336161c28956af8

**Pull request closed without merging**
