### PR TITLE
Load pp and mask from same dir as config

### PR DESCRIPTION
**Pull request by Cybis320**
Here's another way to go about it.

### CODE REVIEW

**Comment by g7gpr** [comment]
Not a fan of this. Mask in Captured directory should always be used in preference, as camera mask in config dir may have changed.

**Comment by Cybis320** [comment]
Problem is I don't see a platepar is the capture directory.

**Comment by Cybis320** [comment]
We could extract a platepar from the json in the capture dir.

**Comment by Cybis320** [comment]
Actually, no mask or platepar in the capture dir. At least, not in prerelease MCL.

**Comment by g7gpr** [comment]
Ah, of course, it gets copied in at the end of capture.

**Comment by Cybis320** [comment]
Not on my end for some reasons. No mask or platepar here in capture dirs. Flux then use no mask and default platepar values from platepar.py with no warnings. I'll look at why they are not there. If you have the code doing the copying handy, that would save me looking for it.

**Comment by Cybis320** [comment]
Looking at other stations running master, I do see the platepar but no mask in Capture. Investigating why I don't have a platepar on my end. In any case, the code shouldn't be allowed to use the default platepar values if no platepar is found.

**Comment by Cybis320** [comment]
Found the issue I think:
If fit_status is False, then the platepar doesn't get copied and flux subsequently use the wrong platepar.

https://github.com/CroatianMeteorNetwork/RMS/blob/441008b356fa203df26d8c5094c82797de5cf7bf/RMS/Reprocess.py#L214-225

**Comment by Cybis320** [comment]
Closing. see #395.

**Pull request closed without merging**
