### PR TITLE
Fix GStreamer Recording Hang

### PR DESCRIPTION
**Pull request by Cybis320**
This update addresses the issue where GStreamer stops recording and hangs until the night session is terminated. The code now verifies that the pipeline has successfully reached the PLAYING state before proceeding further. It allows the camera 10 seconds after a successful ping to initiate an RTSP handshake, then makes up to five retries to start the GStreamer pipeline. If these attempts fail, it falls back to cv2.

### CODE REVIEW

**Comment by g7gpr** [comment]
I'll be able to test this over the next 48 hours on Pi 4 32 bit, Pi 4 64 bit and Debian 12

**Comment by markmac99** [comment]
finally had a chance to deploy this to one of my stations. Apologies, i've been very tied up with a website migration and family business. Will run it for a few days and try to simulate some failure conditions

**Comment by dvida** [comment]
Hi all, any results from the testing? I presume there were no issues?

**Comment by markmac99** [comment]
apologies, meant to confirm earlier. No issues here. Looks good.

**Pull request merged**
