### PR TITLE
Additions to config file

### PR DESCRIPTION
**Pull request by g7gpr**
These support quota management by disc use and deleting captured directories by count.

### CODE REVIEW

**Comment by Cybis320** [comment]
We should try to keep to a 80-character line limit. The comments are exceeding that a little.

**Comment by Cybis320** [comment]
This line break keeps it under 80:
```
; disabling quota management generates the reports, lists the files that would
; be deleted but prevents any action from being taken
; true = disabled, false = enabled

quota_management_disabled: true

; any one of the next three parameters missing or commented out disables the
; quota management each of the parameters is in GB.
```

**Comment by Cybis320** [comment]
@g7gpr,  What is the status on this? I see that the quota management was merged into ConfigReader and DeleteOldObservation but not the associated config options. Should we reopen this PR? See issue #387

**Comment by g7gpr** [comment]
Yes, we should reopen. I deleted my branch as I thought this had been merged.

**Pull request merged**
