### PR TITLE
Add try-except block to Observation summary

### PR DESCRIPTION
**Pull request by Cybis320**
Add try-except block to Observation Summary to troubleshoot reports of reprocess hanging.

### CODE REVIEW

**Comment by g7gpr** [comment]
Based on comments from op I suspect the call to get the time is hanging.

**Comment by Cybis320** [comment]
This?
https://github.com/CroatianMeteorNetwork/RMS/blob/cdec45adf64585586a66399b9336161c28956af8/RMS/Formats/ObservationSummary.py#L501

**Comment by g7gpr** [comment]
https://github.com/CroatianMeteorNetwork/RMS/blob/dcb771e8178bc5310aba61a1eb7d3f8033dbde4c/RMS/Formats/ObservationSummary.py#L234

Here.

**Comment by g7gpr** [comment]
https://github.com/CroatianMeteorNetwork/RMS/blob/dcb771e8178bc5310aba61a1eb7d3f8033dbde4c/RMS/Formats/ObservationSummary.py#L248

This line specifically.

**Comment by g7gpr** [comment]
I wonder if UDP is blocked by station's firewall, and this might cause recvfrom to hang

**Comment by Cybis320** [comment]
I could be. Take a look at the last commit. This should make fetching NTP time safer.

**Comment by g7gpr** [comment]
That's exactly what I had in mind. From here I can't test this on a UDP blocked network, but you should be able to check that function just by running the module.

**Comment by Cybis320** [comment]
Could we just check our suspicion but just running the code vefore and after the PR with no internet connection?

**Comment by g7gpr** [comment]
Tried that on a UDP blocked network. Old version of code threw an exception; which was what I had expected to happen. But is the firewall doing something which is causing it to hang rather than thrown an exception. I'll pull in this version and try again.

**Comment by g7gpr** [comment]
Tested on a UDP blocked network. I couldn't get the timeout clause to activate, it jumped straight to NTP request failed; but I don't have any better ideas than this.

**Comment by g7gpr** [comment]
can you change the wording from "NTP request timed out" to "Time sync check failed". I can think of situations where Chrony / NTP etc would be working fine, but this code might fail.

**Review by g7gpr — APPROVED** [review]

**Pull request merged**
