### PR TITLE
Fix raising an unpickling error during reprocessing

### PR DESCRIPTION
**Pull request by dvida**
Addresses #403 by simply adding pickle.UnpicklingError to the list of checked errors.

### CODE REVIEW

**Comment by satmonkey** [comment]
Hi Denis, 
I cannot reproduce this now. To find the quick solution, I had to delete all pickles and reprocessed the entire night.
I suggest to merge it, as it is rather minor patch.
M.

**Comment by dvida** [comment]
@g7gpr could you give this a quick test? Run capture with the -d option, kill it after a few mins and then restart without the -d option. It's a very simple addition, but we should test before merging into master.

**Comment by g7gpr** [comment]
On AU0004 started capture -d0.2, then pkill python, then startCapture again. 

This is my night, so no reprocessing is taking place. I can deliberately corrupt a pickle, and test like that?

**Comment by dvida** [comment]
Yup, open it in a text file, cut a portion of it, and save. That should do the trick.

**Comment by g7gpr** [comment]
Looks convincing. Reprocess completed successfully otherwise. 

```
Failed loading backup file: rms_queue_bkup_2_vwfbyiie4.pickle
2024/09/05 21:12:56-INFO-QueuedPool-line:204 - Failed loading backup file: rms_queue_bkup_2_vwfbyiie4.pickle
AttributeError("Can't get attribute 'asdfasdf' on <module 'RMS.ConfigReader' from '/home/rms/source/RMS/RMS/ConfigReader.py'>")
2024/09/05 21:12:56-INFO-QueuedPool-line:204 - AttributeError("Can't get attribute 'asdfasdf' on <module 'RMS.ConfigReader' from '/home/rms/source/RMS/RMS/ConfigReader.py'>")
Loaded 1 backed up results...
```

**Comment by g7gpr** [comment]
Is something making sure that the corrupted pickle file gets deleted? It seems to have gone, which is good.

**Comment by dvida** [comment]
All pickles are deleted once the processing finishes. Looking good, merging...

**Comment by g7gpr** [comment]
Working in origin/master

```
2024/09/05 21:35:26-INFO-DetectStarsAndMeteors-line:239 - Starting detection...
The pickle file was corruped and could not be loaded: /home/rms/RMS_data/CapturedFiles/AU0004_20240905_212658_136986/rms_queue_bkup_3_f36dl6dhj.pickle
Loaded 3 backed up results...
2024/09/05 21:35:26-INFO-QueuedPool-line:204 - Loaded 3 backed up results...
Using 3 cores
2024/09/05 21:35:26-INFO-QueuedPool-line:204 - Using 3 cores
2024/09/05 21:35:26-INFO-DetectStarsAndMeteors-line:255 - Adding for detection: FF_AU0004_20240905_212722_034_0000000.fits
2024/09/05 21:35:26-INFO-DetectStarsAndMeteors-line:255 - Adding for detection: FF_AU0004_20240905_212732_275_0000256.fits
Result loaded from backup for input: ['/home/rms/RMS_data/CapturedFiles/AU0004_20240905_212658_136986', 'FF_AU0004_20240905_212722_034_0000000.fits', <RMS.ConfigReader.Config object at 0x7fff869a7210>]
2024/09/05 21:35:26-INFO-QueuedPool-line:204 - Result loaded from backup for input: ['/home/rms/RMS_data/CapturedFiles/AU0004_20240905_212658_136986', 'FF_AU0004_20240905_212722_034_0000000.fits', <RMS.ConfigR>
2024/09/05 21:35:26-INFO-DetectStarsAndMeteors-line:255 - Adding for detection: FF_AU0004_20240905_212742_515_0000512.fits

```

Sorry, I pasted in the check of the undesired behaviour earlier, rather than the check on the fix.

**Pull request merged**
