### PR TITLE
Add summary text file to archive

### PR DESCRIPTION
**Pull request by g7gpr**
This PR is in response to issue #316

### CODE REVIEW

**Comment by g7gpr** [comment]
```date                                 : 20240730_064325
commit                               : 24481635d80ec742e3a9f01bc946f803cef1dc74
merge_parents                        : 073138b2989b7039913e7833470a9291d1eb0f63
hardware_version                     : x86_64
os_version                           : Linux-5.10.0-29-amd64-x86_64-with-glibc2.36
storage_total                        : 232.73GB
storage_used                         : 166.08GB
storage_free                         : 54.76GB
fits_files                           : None
fits_missing                         : None
minutes_missing                      : None
capture_directories                  : None
detections_before_ml                 : None
detections_after_ml                  : None
number_fits_detected                 : None
number_detections_before_ml          : None
number_detections_after_ml           : None
number_fits_detected                 : None
photometry_good                      : None
dropped_frames                       : None
jitter_quality                       : None
dropped_frame_rate                   : None%
last_calculated_fps                  : None
sensor_type                          : None
lens                                 : None
protocol                             : None
media_backend                        : None
```

**Comment by g7gpr** [comment]
```
repo                            : origin/feature/summary_file
date                            : 20240730_154916
commit                          : 54e5a9c4c341c852075698131599f20327ecc1ec
merge_parents                   : 1b6db209ce3cdd060e76d7681aea42c0d574b3cb
hardware_version                : x86_64
storage_total                   : 2749GB
storage_used                    : 45GB
storage_free                    : 2564GB
fits_files                      : None
fits_missing                    : None
minutes_missing                 : None
capture_directories             : 1
detections_before_ml            : 68
detections_after_ml             : 61
number_fits_detected            : 63
number_detections_before_ml     : 68
number_detections_after_ml      : 68
number_fits_detected            : 63
photometry_good                 : True
dropped_frames                  : None
jitter_quality                  : 99.853
dropped_frame_rate              : 3.775%
last_calculated_fps             : None
sensor_type                     : None
camera_pointing                 : az 177.83°, alt 42.09°
camera_fov                      : horizontal 53.59°, vertical 29.93°
lens                            : 6mm
protocol                        : None
media_backend                   : None
```

Reprocess output. Running a capture overnight.

**Comment by Cybis320** [comment]
Great idea. Also, take a look at PR#283 - there might be so useful bits in there.

**Comment by g7gpr** [comment]
Made a git error - closing.

**Pull request closed without merging**
