### PR TITLE
Optionally Use TensorFlow Lite from full TensorFlow Package

### PR DESCRIPTION
**Pull request by Cybis320**
## Background
The tflite-runtime package often lags behind Python releases by a significant amount of time, unlike the full TensorFlow package. This can cause compatibility issues with newer Python versions.  The full TensorFlow package includes tflite which is the only part RMS needs (`tensorflow/lite/python/interpreter`).

## Current Situation
As of this PR:
- TensorFlow supports Python 3.12
- tflite-runtime does not yet support Python 3.12

## Changes
This PR updates `setup.py`, `ConfigReader.py`, `MLFilter.py` and the `requirements.txt` file to enable RMS to use the full TensorFlow package if tflite-runtime is not available. The new installation logic is as follows:

1. Attempt to install tflite-runtime first if tensorflow is not already installed
2. Install tensorflow only if tflite-runtime is not installed and not installable

## Benefits
- Ensures compatibility with newer Python versions
- Maintains preference for the lighter tflite-runtime when possible
- Provides a fallback to full TensorFlow for broader compatibility

## Notes
- This change may slightly increase the package size in environments where tflite-runtime is not available, due to falling back to full TensorFlow.
- Current users on newer Python versions (e.g., 3.12) will automatically use the full TensorFlow package and will remain on the full package.
- Once tflite-runtime catches up, future users on newer Python versions will automatically use the tflite-runtime package if the full package was not installed.

## Related Issues
TensorFlow generates messages at startup about GPU and CUDA. These messages do not affect RMS functionality.

### CODE REVIEW

**Comment by Cybis320** [comment]
That method of conditionally installing TensorFlow failed.

**Comment by satmonkey** [comment]
Have you done any test case? Full TF is difficult to install outside of the docker in general and would not run with the our current tflite model.

**Comment by Cybis320** [comment]
Tested on a Ubuntu 24.04 EliteDesk machine. Installed and works fine for our purpose. The full tf package includes the tflite interpreter, which is what we need. Our model runs just fine on it. 
I installed it with a simple `pip install tensorflow`- there were some complaining about GPU and CUDA, but that doesn't impact us.

Here's the log from last night:
```
024/08/07 12:23:14-INFO-MLFilter-line:409 - ML filtering starting...
2024/08/07 12:23:14-INFO-MLFilter-line:440 - TensorFlow Lite is available.
2024/08/07 12:23:14-INFO-MLFilter-line:442 - Using TensorFlow Lite from full TensorFlow package.
2024/08/07 12:23:14-INFO-MLFilter-line:455 - Creating images for inference...
2024/08/07 12:23:15-INFO-MLFilter-line:459 - Inference starting...
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_065103_056_0356608_1 - Score:  95.8% - meteor
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_065610_473_0364288_1 - Score:  92.6% - meteor
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_070148_632_0372736_1 - Score:  98.7% - meteor
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_073141_901_0417536_1 - Score:  98.9% - meteor
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_074115_746_0431872_1 - Score:  99.9% - meteor
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_082854_728_0503296_1 - Score: 100.0% - meteor
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_085239_095_0538880_1 - Score: 100.0% - meteor
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_085249_343_0539136_1 - Score:  99.1% - meteor
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_085858_244_0548352_1 - Score:   0.8% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_085858_244_0548352_2 - Score:   0.0% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_085858_244_0548352_3 - Score:   0.4% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_090811_595_0562176_1 - Score:  99.9% - meteor
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_091116_045_0566784_1 - Score:  99.7% - meteor
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_091248_271_0569088_1 - Score: 100.0% - meteor
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_092435_330_0586752_1 - Score:   0.0% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_093835_604_0607744_1 - Score: 100.0% - meteor
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_094444_505_0616960_1 - Score:  99.9% - meteor
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_094900_686_0623360_1 - Score:  99.9% - meteor
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_100006_756_0640000_1 - Score: 100.0% - meteor
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_100118_487_0641792_1 - Score: 100.0% - meteor
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_104826_725_0712448_1 - Score:  99.1% - meteor
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110744_664_0741376_1 - Score:   0.1% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110744_664_0741376_2 - Score:   0.0% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110744_664_0741376_3 - Score:   0.0% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110744_664_0741376_4 - Score:   0.3% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110744_664_0741376_5 - Score:   0.0% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_1 - Score:  84.0% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_2 - Score:   0.2% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_3 - Score:   0.3% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_4 - Score:   0.0% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_5 - Score:   0.0% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_6 - Score:   0.4% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_7 - Score:   3.9% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_8 - Score:   0.0% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_9 - Score:   1.2% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_10 - Score:   0.0% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_11 - Score:   0.4% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_12 - Score:   0.1% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_13 - Score:   0.2% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_14 - Score:   1.7% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_15 - Score:   0.0% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_16 - Score:   0.0% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_17 - Score:   3.3% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_18 - Score:   1.7% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_19 - Score:   0.1% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_20 - Score:   0.0% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_21 - Score:   0.1% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_22 - Score:   0.1% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_23 - Score:   0.2% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_24 - Score:   0.6% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_25 - Score:   0.0% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_26 - Score:   0.2% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_27 - Score:   0.6% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_28 - Score:   0.3% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_29 - Score:   0.0% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110754_911_0741632_30 - Score:   0.5% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110805_159_0741888_1 - Score:  92.9% - meteor
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110805_159_0741888_2 - Score:   0.0% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110805_159_0741888_3 - Score:   0.1% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110805_159_0741888_4 - Score:   0.1% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110805_159_0741888_5 - Score:   0.0% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110805_159_0741888_6 - Score:   0.0% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110805_159_0741888_7 - Score:   0.0% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110805_159_0741888_8 - Score:   0.0% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110805_159_0741888_9 - Score:   0.1% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110805_159_0741888_10 - Score:   0.1% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110805_159_0741888_11 - Score:   0.0% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110805_159_0741888_12 - Score:   0.3% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110805_159_0741888_13 - Score:   0.0% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110805_159_0741888_14 - Score:   0.1% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110805_159_0741888_15 - Score:   0.0% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110805_159_0741888_16 - Score:   0.0% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_110805_159_0741888_17 - Score:   0.0% - artefact
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_113037_795_0775680_1 - Score:  99.7% - meteor
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_113626_201_0784384_1 - Score: 100.0% - meteor
2024/08/07 12:23:15-INFO-MLFilter-line:538 - FF_US9995_20240807_114935_239_0804096_1 - Score:  99.6% - meteor
2024/08/07 12:23:15-INFO-MLFilter-line:559 - Saving a filtered FTPdetectinfo file...
2024/08/07 12:23:15-INFO-MLFilter-line:570 - FTPdetectinfo filtered, 21/76 detections classified as real meteors

```

**Comment by Cybis320** [comment]
Still no tflite-runtime support for python 3.12. The last tflite-runtime update was almost a year ago...

**Comment by dvida** [comment]
Should we merge this into the contrail branch, as tf might be used for training? This way it will also get some testing.

**Comment by dvida** [comment]
Will do - the tflite entry in the requirements.txt file needs to be improved. It needs to install it on the Pi and the full-blown tensorflow package on PCs. I can make the edit but it will need to get tested.

**Comment by satmonkey** [comment]
Is this something which can help us?
https://github.com/tensorflow/tensorflow/issues/62003#issuecomment-2384741963

**Comment by satmonkey** [comment]
Maybe to build the wheels we need?
https://ai.google.dev/edge/litert/build/cmake_pip

**Comment by satmonkey** [comment]
I have tested pip install tensorflow on the Pi4 and it takes hours.
Did not try the inference yet. Maybe to avoid loading full TF on the non-PC platform at all?

**Comment by dvida** [comment]
I changed the line to:
```
tensorflow; python_version >= '3.12' and platform_machine != "armv6l" and platform_machine != "armv7l" and platform_machine != "aarch64" and platform_machine != "arm64"
```

**Comment by bperseghetti** [comment]
> Is this something which can help us?
> https://github.com/tensorflow/tensorflow/issues/62003#issuecomment-2384741963
> 

If you were wanting to use what I did in https://github.com/tensorflow/tensorflow/issues/62003#issuecomment-2384741963 I could try to add it in a PR, but since I used 24.04 as the docker cross-compiler it does break their other backwards compatibility build system due to some upstream changes in how installing with pip on 24.04 and other packages changes/deprecations in 3.12.

**Pull request merged**
