### PR TITLE
Stop reprocessing if capture time

### PR DESCRIPTION
**Pull request by g7gpr**
Wrt to Issue #171, allows at least one directory to be reprocessed, but it it is time to capture does not allow any more to be processed, until the next day.

### CODE REVIEW

**Comment by dvida** [comment]
So I'm torn on this one because I can see this get stuck in an infinite loop of half-processed observations. I'd rather have fully processed nights ASAP than wait for them to be processed or perhaps even deleted by the disk management code.

**Comment by g7gpr** [comment]
It's perhaps something I'll keep for my own stations. Up to you.

**Comment by dvida** [comment]
You can add that as an option in the config file, with it being disabled by default.

**Comment by g7gpr** [comment]
This can't get stuck in a loop of half processed observations. If an observation starts to get reprocessed it will not be interrupted, even if this means that capture start is delayed; the break occurs at the end of processing one night of data, not during the processing of a night.

**Comment by dvida** [comment]
I guess it will always reprocess one, but not more than one?

**Comment by g7gpr** [comment]
If reprocess is called, then it will always reprocess one unprocessed directory, as the conditional break comes after the function that does the reprocessing. If capture is not due to start, then it will start working on the next directory. So capture may end up starting later, but it should not reprocess all through the night.

One station got turned off at dawn each morning as it had been moved onto a circuit controlled by a photocell. When this problem was resolved, it did not capture anything for four days while it worked through all the broken directories. This is to protect against that situation.

**Comment by dvida** [comment]
Okay, I think this sounds reasonable now.

**Pull request merged**
