### PR TITLE
small change to SkyFit2 to save the FF name in the state file.

### LINKED ISSUE #262: State file doesn't contain FF name
The state file saved by SkyFit2 does not contain  the name of the FF file. 
The file name IS included if its an FR file but not if its an FF. 
This causes a problem when more than one FF file is present, for example bracketing FFs to allow better platepar refinement, or when the fireball is split across two FF files.

### PR DESCRIPTION
**Pull request by markmac99**
I've amended skyfit2 to include the FF filename in the state file. 
Now, if you run SkyFit2 on a folder containing more than one FF file, you can either
a) use the folder as before, move between FF files and then work on the one you want to use; or
b) load the state file. In this case, the right FF file is automatically loaded for further analysis

I've done some testing with fireballs without any issues, but would appreciate further review / input.

Closes #262

### CODE REVIEW

**Comment by satmonkey** [comment]
almost perfect!
however, when using the --fr switch, and starting the fireball reduction on the FR file, restoring the state jumps to the FF file, not FR. It allows to resume the reduction though, but this is a minor side effect.

**Comment by dvida** [comment]
Great! Have you tried opening old state files that were generated with previous version of skyfit?

**Comment by markmac99** [comment]
@dvida I think so, but i will double check just in case.

**Comment by satmonkey** [comment]
does not work with old state files here. Takes the 1st FF file as default.

**Comment by dvida** [comment]
Good, as long as it doesn't throw an error. I'll now do a final test on non-RMS data and merge.

**Comment by markmac99** [comment]
@dvida confirmed that when i load an older state file, the programme behaves as previously and loads the 1st available FF file. 

This means that could be the wrong image for the state, but this is as expected since the correct filename isn't stored in the state.

**Review by satmonkey — APPROVED** [review]

**Comment by markmac99** [comment]
@satmonkey yea thats as expected because the ff name is not available in the state :) so the behaviour is as it was previously (all that can be done).

**Comment by satmonkey** [comment]
I got it :) good job

**Comment by dvida** [comment]
Sorry to reopen this - has anyone tried moving the data directory to a different path? Will this new feature work then? E.g. the use cause might be when sharing the reduction with someone.

**Comment by satmonkey** [comment]
yes, this works with me, too

**Pull request merged**
