### PR TITLE
Fix #366: Resolve Multicam repo folder location bug

### LINKED ISSUE #366: Prerelease: ObservationSummary Error on Multicam station
On start capture with prerelease:
```
2024/08/18 15:54:43-ERROR-DownloadPlatepar-line:46 - Connecting to server failed!
2024/08/18 15:54:43-INFO-Reprocess-line:78 - Loaded platepar from RMS directory: platepar_cmn2010.cal
2024/08/18 15:54:43-INFO-StartCapture-line:273 - Initializing frame buffers...
2024/08/18 15:54:43-INFO-StartCapture-line:297 - Initializing frame buffers done!
Loaded 0 backed up results...
2024/08/18 15:54:44-INFO-QueuedPool-line:204 - Loaded 0 backed up results...
Using 1 cores
2024/08/18 15:54:44-INFO-QueuedPool-line:204 - Using 1 cores
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/bolide/source/RMS/RMS/StartCapture.py", line 873, in <module>
    runCapture(config, duration=duration, nodetect=cml_args.nodetect, upload_manager=upload_manager, \
  File "/home/bolide/source/RMS/RMS/StartCapture.py", line 386, in runCapture
    log.info(startObservationSummaryReport(config, duration, force_delete=False))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bolide/source/RMS/RMS/Formats/ObservationSummary.py", line 162, in startObservationSummaryReport
    repo = git.Repo(search_parent_directories=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bolide/vRMS/lib/python3.12/site-packages/git/repo/base.py", line 289, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /home/bolide/source/Stations/US9992
```

### PR DESCRIPTION
**Pull request by Cybis320**
#366  The repo is not found on the parent dir on multicam station. Would it be sufficient to point to ~/source/RMS and wrap it in a try?

### CODE REVIEW

**Comment by g7gpr** [comment]
Yes, that works. Thanks for picking this up.

**Comment by g7gpr** [comment]
In your start script, is it changing directory out of ~/source/RMS before launching StartCapture? That was causing all kinds of problems, for example picking up cached and out of date versions of code rather than the version in ~/source/RMS

**Review by g7gpr — APPROVED** [review]
Thanks, this looks good. Can you look at your start scripts and see if it is trying to start StartCapture in a directory other than ~/source/RMS, rather than starting in ~/source/RMS and using the -c option to point to the correct config file?

**Comment by Cybis320** [comment]
Good catch, it's using the old script which starts from  `~/source/Stations/$1`.
But why on earth didn't the scripts update when everything else did??

**Comment by g7gpr** [comment]
Unknown, however thank you for this fix.

**Pull request merged**
