### PR TITLE
Radiant colours

### PR DESCRIPTION
**Pull request by robagar**
Hi!

Just a small change for the radiant graphic generation - using a colour map generated from the shower names so that the region and activity bar colours match.

Here's an example:
UK003C_20210727_204905_886265_radiants

### CODE REVIEW

**Comment by robagar** [comment]
updated so that the meteors are also the same colour (or gray for sporadics)
UK003C_20210727_204905_886265_radiants

**Comment by robagar** [comment]
I've made the great circle track the same colours to, it really makes the showers stand out...
UK003C_20210727_204905_886265_radiants
Also sporadics are more visible white

**Comment by markmac99** [comment]
Looks good to me.  Have you tested it with python 2.7? We do still have some users on this version (on the Pi3 platform).

**Comment by robagar** [comment]
Another small tweak - shuffle the colours to make them more distinct
UK003C_20210801_204039_675537_radiants

**Comment by robagar** [comment]
I don't have a Python 2 environment to test against, but there's nothing that should cause problems... are you able to test it?

**Comment by markmac99** [comment]
I'll see if i can test it on my old Pi3. I just upgraded my 4th camera to a pi4 this weekend so i have a spare python 2.7 envt now.

**Comment by dvida** [comment]
Hi Rob,
this looks great, I love the new colour scheme!
One question: Do we need the RerunShowerAssociation.py file? This is just the last part of the ShowerAssociation script extracted into a separate file, no?

**Comment by robagar** [comment]
Yeah, I just made that to test the radiant graphic generation, so not needed for actual use

**Comment by robagar** [comment]
...want me to delete it before merging?

**Comment by dvida** [comment]
That'd be great! We're still waiting for @markmac99 to test it on his Pi3. If it all goes well, I'll merge it then.

**Comment by markmac99** [comment]
Tested with python 2.7 on Jessie, works well. Useful improvement, thanks! 
UK000F_20210804_202829_994811_radiants

**Comment by robagar** [comment]
Excellent! thanks for testing it Mark

**Comment by dvida** [comment]
Great job, thank you!

**Pull request merged**
